# Generated by Django 3.0.7 on 2020-08-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(default='', max_length=250)),
                ('url', models.CharField(default='', max_length=250)),
                ('title', models.CharField(default='', max_length=250)),
                ('image_content_url', models.CharField(default='', max_length=250)),
                ('author', models.CharField(default='', max_length=250)),
                ('published_time', models.CharField(default='', max_length=250)),
                ('content', models.TextField()),
            ],
        ),
    ]
