# Generated by Django 3.0.7 on 2020-08-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source_Of_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(default='', max_length=100)),
                ('page_url', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
