# Generated by Django 3.0.7 on 2020-08-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_news', '0002_source_of_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skip_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image_content_url',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='articles',
            name='page_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='articles',
            name='published_time',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='articles',
            name='url',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='source_of_news',
            name='page_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='source_of_news',
            name='page_url',
            field=models.CharField(max_length=250),
        ),
    ]
