# Generated by Django 3.0.7 on 2020-08-29 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_news', '0004_auto_20200827_0504'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articles',
            unique_together={('url', 'title')},
        ),
    ]
