# Generated by Django 3.1 on 2020-09-12 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_news', '0006_auto_20200829_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='content',
        ),
    ]
